### PR TITLE
[Sprint: 50] XD-2929: Added example of a nested job module in Spring XD

### PR DESCRIPTION
**Pull request by mminella**

### CODE REVIEW

**Comment by trisberg** [comment]
Wonder what this job config looks like in XML?

**Comment by trisberg** [comment]
It's very barebones. Maybe we could have two jobs where one passes the time it was executed to the second job that could just print when the first job was executed. Or something like that. I would think that communication between jobs would be interesting to anyone attempting this nested approach.

**Comment by mminella** [comment]
1. I was under the understanding that new demos/samples should be java config based which is why I went that route.
2. It is very bare bones, but my intent isn't to demonstrate or even advocate for the communication between jobs.  I was thinking more of a building blocks approach.  I guess we could name this batch-nested-simple and add a more complex one that addresses communication options for communication between jobs (to be honest, I'd have to think about what that should look like anyways).

**Comment by trisberg** [comment]
1. left out the smiley :)
2. fair enough - merging as is, we can build more complex sample later if needed

**Comment by trisberg** [comment]
Merged vi commit 99c8c14447e2703574e600c85bbd47c244250ffb

**Pull request closed without merging**
